name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Restore dependencies
      run: dotnet restore ./src/WinForms.NullableBinding.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release ./src/WinForms.NullableBinding.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ./src/WinForms.NullableBinding.sln

    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }} -o ./artifacts ./src/WinForms.NullableBinding.sln

    - name: Push NuGet package
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
